global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'processor'
    static_configs:
      - targets: ['processor:8080']

  - job_name: 'analytics-api'
    static_configs:
      - targets: ['analytics-api:8003']
