{
 "title": "Analytics API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ANALYTICS_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ANALYTICS_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ANALYTICS_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "ANALYTICS_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Database/Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DB Queries Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ANALYTICS_db_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ANALYTICS_db_query_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ANALYTICS_db_query_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(ANALYTICS_db_query_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "ANALYTICS_db_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(ANALYTICS_cache_hits_total / (ANALYTICS_cache_misses_total + ANALYTICS_cache_hits_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}