{
 "title": "Consumer",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Top Failure Reasons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(5, sum by (reason) (rate(CONSUMER_messages_rejected_total[10s])))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validation Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(CONSUMER_messages_validated_total[10s]) / \n(rate(CONSUMER_messages_validated_total[10s]) + rate(CONSUMER_messages_rejected_total[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Messages Published Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(CONSUMER_kafka_messages_published_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Validated Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(CONSUMER_messages_validated_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Consumed/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(CONSUMER_kafka_messages_consumed_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enrichment Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(CONSUMER_enrichment_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(CONSUMER_enrichment_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(CONSUMER_enrichment_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}