{
 "title": "Producer",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Messages Published/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(PRODUCER_kafka_messages_published_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Publish Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(PRODUCER_kafka_publish_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(PRODUCER_kafka_publish_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(PRODUCER_kafka_publish_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafaka Publish Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "PRODUCER_kafka_publish_errors_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}